lib/ozone_web/router.ex
defmodule OzoneWeb.Router do
  use OzoneWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  # This plug will look for a Guardian token in the session in the default location
  # Then it will attempt to load the resource found in the JWT.
  # If it doesn't find a JWT in the default location it doesn't do anything
  pipeline :browser_auth do
    plug Guardian.Plug.VerifySession
    plug Guardian.Plug.LoadResource
    plug :put_user_token
  end

  # We need this pipeline to load the token when we're impersonating.
  # We don't want to load the resource though, just verify the token
  pipeline :impersonation_browser_auth do
    plug Guardian.Plug.VerifySession, key: :admin
  end

  # This pipeline if intended for API requests and looks for the JWT in the "Authorization" header
  # In this case, it should be prefixed with "Bearer" so that it's looking for
  # Authorization: Bearer <jwt>
  pipeline :api_auth do
    plug Guardian.Plug.VerifyHeader, realm: "Bearer"
    plug Guardian.Plug.LoadResource
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", OzoneWeb do
    pipe_through [:browser, :browser_auth, :impersonation_browser_auth]

    resources "/users", UserController
    resources "/boards", BoardController do
      resources "/topics", TopicController, only: [:index, :create, :update, :delete]
    end
    get "/", PageController, :index
  end

  scope "/auth", OzoneWeb do
    pipe_through [:browser, :browser_auth]

    get "/:provider", AuthController, :login
    get "/:provider/callback", AuthController, :callback
    post "/:provider/callback", AuthController, :callback
    delete "/logout", AuthController, :logout
  end

  scope "/api", OzoneWeb do
    pipe_through [:api, :api_auth]
  end

  defp put_user_token(conn, _) do
    if current_user = Guardian.Plug.current_resource(conn, :default) do
      token = Phoenix.Token.sign(conn, "user_web_socket", current_user.id)
      assign(conn, :user_token, token)
    else
      conn
    end
  end
end

lib/ozone/boards/board.ex
defmodule Ozone.Boards.Board do
  use Ecto.Schema
  import Ecto.Changeset
  alias Ozone.Boards.Board

  @primary_key {:id, :binary_id, autogenerate: true, read_after_write: true}
  @foreign_key_type :binary_id
  schema "boards" do
    field :name, :string

    belongs_to :user, Ozone.User
    has_many :topics, Ozone.Boards.Topic

    timestamps()
  end

  @doc false
  def changeset(%Board{} = board, attrs) do
    board
    |> cast(attrs, [:name])
    |> validate_required([:name])
  end
end

lib/ozone/boards/boards.ex
defmodule Ozone.Boards do
  @moduledoc """
  The Boards context.
  """

  import Ecto
  import Ecto.Query, warn: false
  alias Ozone.Repo

  alias Ozone.Boards.Board
  alias Ozone.Boards.Topic

  @doc """
  Returns the list of boards.

  ## Examples

      iex> list_boards()
      [%Board{}, ...]

  """
  def list_boards(user) do
    Repo.all(from(board in Board, where: board.user_id == ^user.id))
  end

  @doc """
  Gets a single board.

  Raises `Ecto.NoResultsError` if the Board does not exist.

  ## Examples

      iex> get_board!(123)
      %Board{}

      iex> get_board!(456)
      ** (Ecto.NoResultsError)

  """
  def get_board!(user, id), do: Repo.get!(assoc(user, :boards), id)

  @doc """
  Creates a board.

  ## Examples

      iex> create_board(%{field: value})
      {:ok, %Board{}}

      iex> create_board(%{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def create_board(user, attrs \\ %{}) do
    user
    |> Ecto.build_assoc(:boards)
    |> Board.changeset(attrs)
    |> Repo.insert()
  end

  @doc """
  Updates a board.

  ## Examples

      iex> update_board(board, %{field: new_value})
      {:ok, %Board{}}

      iex> update_board(board, %{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def update_board(%Board{} = board, attrs) do
    board
    |> Board.changeset(attrs)
    |> Repo.update()
  end

  @doc """
  Deletes a Board.

  ## Examples

      iex> delete_board(board)
      {:ok, %Board{}}

      iex> delete_board(board)
      {:error, %Ecto.Changeset{}}

  """
  def delete_board(%Board{} = board) do
    Repo.delete(board)
  end

  @doc """
  Returns an `%Ecto.Changeset{}` for tracking board changes.

  ## Examples

      iex> change_board(board)
      %Ecto.Changeset{source: %Board{}}

  """
  def change_board(%Board{} = board) do
    Board.changeset(board, %{})
  end

  alias Ozone.Boards.Topic

  @doc """
  Returns the list of topics.

  ## Examples

      iex> list_topics()
      [%Topic{}, ...]

  """
  def list_topics do
    Repo.all(Topic)
  end

  def get_topics!(board), do: Repo.all(assoc(board, :topics))

  @doc """
  Gets a single topic.

  Raises `Ecto.NoResultsError` if the Topic does not exist.

  ## Examples

      iex> get_topic!(123)
      %Topic{}

      iex> get_topic!(456)
      ** (Ecto.NoResultsError)

  """
  def get_topic!(id), do: Repo.get!(Topic, id)

  @doc """
  Creates a topic.

  ## Examples

      iex> create_topic(%{field: value})
      {:ok, %Topic{}}

      iex> create_topic(%{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def create_topic(attrs \\ %{}) do
    %Topic{}
    |> Topic.changeset(attrs)
    |> Repo.insert()
  end

  @doc """
  Updates a topic.

  ## Examples

      iex> update_topic(topic, %{field: new_value})
      {:ok, %Topic{}}

      iex> update_topic(topic, %{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def update_topic(%Topic{} = topic, attrs) do
    topic
    |> Topic.changeset(attrs)
    |> Repo.update()
  end

  @doc """
  Deletes a Topic.

  ## Examples

      iex> delete_topic(topic)
      {:ok, %Topic{}}

      iex> delete_topic(topic)
      {:error, %Ecto.Changeset{}}

  """
  def delete_topic(%Topic{} = topic) do
    Repo.delete(topic)
  end

  @doc """
  Returns an `%Ecto.Changeset{}` for tracking topic changes.

  ## Examples

      iex> change_topic(topic)
      %Ecto.Changeset{source: %Topic{}}

  """
  def change_topic(%Topic{} = topic, attrs \\ %{}) do
    Topic.changeset(topic, attrs)
  end

  @doc """
  Returns the list of boards.

  ## Examples

      iex> list_boards()
      [%Board{}, ...]

  """
  def get_board_topic(board_id, topic_id) do
    try do
      Repo.get_by(Topic, id: topic_id, board_id: board_id)
    rescue
      _ -> nil
    end
  end
end

lib/ozone/boards/topic.ex
defmodule Ozone.Boards.Topic do
  use Ecto.Schema
  import Ecto.Changeset
  alias Ozone.Boards.Topic

  @primary_key {:id, :binary_id, autogenerate: true}
  @foreign_key_type :binary_id

  schema "topics" do
    field :body, :string
    field :votes, :integer, default: 0
    belongs_to :user, Ozone.User
    belongs_to :board, Ozone.Boards.Board

    timestamps()
  end

  @doc false
  def changeset(%Topic{} = topic, attrs) do
    topic
    |> cast(attrs, [:body, :votes, :user_id, :board_id])
    |> foreign_key_constraint(:user_id)
    |> foreign_key_constraint(:board_id)
    |> validate_required([:body])
  end

  def votes_changeset(model, votes) do
    model
    |> change(%{votes: votes})
  end
end

lib/ozone_web/controllers/board_controller.ex
defmodule OzoneWeb.BoardController do
  use OzoneWeb, :controller

  alias Ozone.Boards
  alias Ozone.Boards.Board
  alias Ozone.Boards.Topic

  plug(Guardian.Plug.EnsureAuthenticated, handler: __MODULE__)

  def index(conn, _params, current_user, _claims) do
    boards = Boards.list_boards(current_user)
    render(conn, "index.html", current_user: current_user, boards: boards)
  end

  def new(conn, _params, current_user, _claims) do
    changeset = Boards.change_board(%Board{})
    render(conn, "new.html", current_user: current_user, changeset: changeset)
  end

  def create(conn, %{"board" => board_params}, current_user, _claims) do
    case Boards.create_board(current_user, board_params) do
      {:ok, board} ->
        conn
        |> put_flash(:info, "Board created successfully.")
        |> redirect(to: board_path(conn, :show, board))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", current_user: current_user, changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}, current_user, _claims) do
    board = Boards.get_board!(current_user, id)
    changeset = Ozone.Boards.change_topic(%Topic{}, %{board_id: board.id})
    topics = Boards.get_topics!(board)

    render(
      conn,
      "show.html",
      current_user: current_user,
      board: board,
      topics: topics,
      changeset: changeset
    )
  end

  def edit(conn, %{"id" => id}, current_user, _claims) do
    board = Boards.get_board!(current_user, id)
    changeset = Boards.change_board(board)
    render(conn, "edit.html", current_user: current_user, board: board, changeset: changeset)
  end

  def update(conn, %{"id" => id, "board" => board_params}, current_user, _claims) do
    board = Boards.get_board!(current_user, id)

    case Boards.update_board(board, board_params) do
      {:ok, board} ->
        conn
        |> put_flash(:info, "Board updated successfully.")
        |> redirect(to: board_path(conn, :show, board))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", current_user: current_user, board: board, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}, current_user, _claims) do
    board = Boards.get_board!(current_user, id)
    {:ok, _board} = Boards.delete_board(board)

    conn
    |> put_flash(:info, "Board deleted successfully.")
    |> redirect(to: board_path(conn, :index))
  end

  def unauthenticated(conn, _params) do
    conn
    |> put_flash(:info, "Authentication required")
    |> redirect(to: "/")
  end
end

lib/ozone_web/views/board_view.ex
defmodule OzoneWeb.BoardView do
  use OzoneWeb, :view
end

lib/ozone_web/templates/board/edit.html.eex
<h2>Edit Board</h2>

<%= render "form.html", Map.put(assigns, :action, board_path(@conn, :update, @board)) %>

<span><%= link "Back", to: board_path(@conn, :index) %></span>

lib/ozone_web/templates/board/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="form-group">
    <%= label f, :name, class: "control-label" %>
    <%= text_input f, :name, class: "form-control" %>
    <%= error_tag f, :name %>
  </div>

  <div class="form-group">
    <%= submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

lib/ozone_web/templates/board/index.html.eex
<h2>Listing Boards</h2>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for board <- @boards do %>
    <tr>
      <td><%= board.name %></td>

      <td class="text-right">
        <span><%= link "Show", to: board_path(@conn, :show, board), class: "btn btn-default btn-xs" %></span>
        <span><%= link "Edit", to: board_path(@conn, :edit, board), class: "btn btn-default btn-xs" %></span>
        <span><%= link "Delete", to: board_path(@conn, :delete, board), method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-danger btn-xs" %></span>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<span><%= link "New Board", to: board_path(@conn, :new) %></span>

lib/ozone_web/templates/board/new.html.eex
<h2>New Board</h2>

<%= render "form.html", Map.put(assigns, :action, board_path(@conn, :create)) %>

<span><%= link "Back", to: board_path(@conn, :index) %></span>

lib/ozone_web/templates/board/show.html.eex
<div id="board" data-id="<%= @board.id %>">
  <h2><%= @board.name %></h2>
  <span><%= link "Edit", to: board_path(@conn, :edit, @board) %></span>
  <span><%= link "Back", to: board_path(@conn, :index) %></span>
</div>
<div id="board-topics">
  <section name="topics">
    <div class="panel panel-default">
      <div class="panel-heading">Topics</div>
      <ul id="board-topics-container" class="list-group">
        <%= for topic <- @topics do %>
          <li class="list-group-item topic clear-both" data-id="<%= topic.id %>">
            <a
              class="vote"
              data-id="<%= topic.id %>"
              onClick="if(window.boardInstance) { window.boardInstance.voteOnTopic('<%= @board.id %>', '<%= topic.id %>') }"
            >
              <span class="votes" data-votes="<%= topic.votes %>">(<%= topic.votes || 0 %>)</span>
              <i class="far fa-heart"></i>
            </a>
            <%= topic.body %>
            <a class="delete-topic pull-right"
               data-id="<%= topic.id %>"
               onClick="if(window.boardInstance) { window.boardInstance.deleteTopic('<%= @board.id %>', '<%= topic.id %>') }"
            >
              <i class="fas fa-trash"></i>
            </a>
          </li>
        <% end %>
      </ul>
    </div>
  </section>
  <h3>New Topic</h3>
  <%= render "topic_form.html", Map.put(assigns, :action, board_topic_path(@conn, :create, @board)) %>
</div>
<div id="board-chat">
  <h3>Chat</h3>
  <ul id="board-chat-container" class="list-group">
  </ul>
  <div class="input-group chat-msg-fields">
    <input id="board-chat-msg-input" class="form-control" type="text" name="board-chat-msg" placeholder="Send a message...">
    <div class="input-group-btn">
      <button type="button" id="board-chat-msg-send" name="send-msg-btn" class="btn btn-info">Send</button>
    </div>
  </div>
</div>

lib/ozone_web/templates/board/topic_form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="form-group">
    <%= label f, :body, class: "control-label" %>
    <%= textarea f, :body, class: "form-control" %>
    <%= error_tag f, :body %>
  </div>

  <div class="form-group">
    <%= submit "Submit", class: "btn btn-primary", id: "topic-submit-btn" %>
  </div>
<% end %>